export default {
  data() {
    return {
      portfolios: [
        {
          id: 1,
          img: "/assets/images/portfolio/smo-logo-1.png",
          title: "SCHOOLMATE ONLINE",
          project: "School Management System",
          client: "Envato",
          language: "HTML,CSS,Javascript",
          preview: "www.schoolmate-online.net",
          previewLink: "https://www.schoolmate-online.net/",
          alt: "Portfolio",
          description1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
          description2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
          description3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
          description4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        },
        {
          id: 2,
          img: "/assets/images/portfolio/one-pampanga-logo-1.png",
          title: "ONE PAMPANGA",
          project: "Business Directory Listing",
          client: "Envato",
          language: "Camtasia Studio",
          preview: "www.onepampanga.com",
          previewLink: "https://onepampanga.com/",
          alt: "One Pampanga",
          description1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
          description2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
          description3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
          description4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        },
        {
          id: 3,
          img: "/assets/images/portfolio/one-zambales-logo-horizontal.png",
          title: "ONE ZAMBALES",
          project: "Business Directory Listing",
          client: "Instagram",
          language: "Slider Group",
          preview: "www.onezambales.com",
          previewLink: "https://onezambales.com/",
          alt: "One Zambales",
          description1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
          description2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
          description3: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
          description4: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        },
        // {
        //   id: 4,
        //   img: "/assets/images/portfolio/project-4.jpg",
        //   title: "DRIBBBLE PROJECT",
        //   project: "Project Shoot",
        //   client: "dribbble",
        //   language: "React",
        //   preview: "www.dribbble.com",
        //   previewLink: "https://dribbble.com/ib-themes",
        //   alt: "Portfolio",
        // },
        // {
        //   id: 5,
        //   img: "/assets/images/portfolio/project-5.jpg",
        //   title: "BEHANCE PROJECT",
        //   project: "Live Shoot",
        //   client: "Behance",
        //   language: "React,Bootstrap",
        //   preview: "www.behance.com",
        //   previewLink: "https://www.behance.net/ib-themes",
        //   alt: "Portfolio",
        // },
        // {
        //   id: 6,
        //   img: "/assets/images/portfolio/project-6.jpg",
        //   title: "SAAS PROJECT",
        //   project: "Web Application",
        //   client: "Themeforest",
        //   language: "HTML, CSS, ReactJs",
        //   preview: "www.themeforest.com",
        //   previewLink: "https://themeforest.net/item/deski-saas-software-react-template/33799794",
        //   alt: "Portfolio",
        // },
        // {
        //   id: 7,
        //   img: "/assets/images/portfolio/project-7.jpg",
        //   title: "MOCKUP PROJECT",
        //   project: "Website",
        //   client: "Pexels",
        //   language: "Adobe Photoshop",
        //   preview: "www.pexels.com",
        //   previewLink: "https://www.pexels.com/",
        //   alt: "Portfolio",
        // },
        // {
        //   id: 8,
        //   img: "/assets/images/portfolio/project-8.jpg",
        //   title: "FACEBOOK PROJECT",
        //   project: "Shoot",
        //   client: "Facebook",
        //   language: "Reactjs",
        //   preview: "www.facebook.com",
        //   previewLink: "https://www.facebook.com/ibthemes",
        //   alt: "Portfolio",
        // },
        // {
        //   id: 9,
        //   img: "/assets/images/portfolio/project-9.jpg",
        //   title: "LINKEDIN PROJECT",
        //   project: "Website",
        //   client: "Linkedin",
        //   language: "Vue 3",
        //   preview: "www.linkedin.com",
        //   previewLink: "https://www.linkedin.com/in/ib-themes-company-469408207/recent-activity/shares/",
        //   alt: "Portfolio",
        // },
      ],
    };
  },
};
